
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'datavault4dbt'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'datavault4dbt'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  datavault4dbt:
    # Config indicated by + and applies to all files under models/example/
    dbt_stg:
      +schema: <name of your Staging schema>
      +materialized: view
    raw_vault:
      +schema: <name of your RDV schema>
      +materialized: table

vars:
  datavault4dbt.hash: 'MD5'
  datavault4dbt.hash_datatype: 'STRING'
  datavault4dbt.beginning_of_all_times: {"default":"0001-01-01T00-00-01","snowflake":"0001-01-01T00:00:01"}
  datavault4dbt.end_of_all_times: {"default":"8888-12-31T23-59-59","snowflake":"8888-12-31T23:59:59"}
  datavault4dbt.timestamp_format: {"default":"%Y-%m-%dT%H-%M-%S","snowflake":"YYYY-MM-DDTHH24:MI:SS"}
  datavault4dbt.hashkey_input_case_sensitive: FALSE
  datavault4dbt.hashdiff_input_case_sensitive: TRUE
  datavault4dbt.ldts_alias: 'ldts'
  datavault4dbt.rsrc_alias: 'rsrc'
  datavault4dbt.ledts_alias: 'ledts'
  datavault4dbt.eff_from_alias: 'effective_from'
  datavault4dbt.eff_to_alias: 'effective_to'
  datavault4dbt.default_ghost_rec_rsrc: 'SYSTEM'
